version: '3.9'
services:
  shiny:
    build: .
    restart: unless-stopped
    deploy:
      replicas: 4
    volumes:
      - ./:/reelgene
      # export USER_ID=$(id -u)
      - "/run/user/${USER_ID}/docker.sock:/var/run/docker.sock"
    environment:
      - REELGENE_DOCKER=1
    ports:
      - 127.0.0.1:8001-8004:8000
