version: '3.9'
services:
  shiny:
    build: .
    restart: unless-stopped
    deploy:
      replicas: 4
    volumes:
      - ./:/reelgene
    environment:
      - REELGENE_DOCKER=1
    ports:
      - 127.0.0.1:8001-8004:8000
